name: Update Compatibility List
on:
  issues:
    types: [labeled, unlabeled, edited, closed]

concurrency:
  group: compat-list-update
  cancel-in-progress: false

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'verified')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # rebasing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Generator
        run: python scripts/generate_list.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Citron-Bot'
          git config --global user.email 'bot@citron-emu.org'
          git add compatibility_list.json
    
          # Only commit if there are actually changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update list from Issue #${{ github.event.issue.number }}"
    
          git pull --rebase -Xours origin main
    
          git push origin main
